# Generated by Django 5.2.3 on 2025-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hotelimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='ameneties',
            new_name='amenities',
        ),
    ]
