# Generated by Django 5.2 on 2025-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
