# Generated by Django 5.2 on 2025-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotelbooking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
